### ISSUE TITLE
yeoman error EACCES: permission denied, mkdir '/Users/radjiv/.config/configstore'

### ISSUE THREAD

**Issue by radjivC** [yeoman/yeoman.io#477]
Hi everyone,
When I installed yeoman, the yeoman doctor tell me everything is ok:

```
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
```

when I use the command yo, an error happens
````
 yo -v
/usr/local/lib/node_modules/yo/node_modules/configstore/node_modules/mkdirp/index.js:90
                    throw err0;
                          ^
Error: EACCES: permission denied, mkdir '/Users/radjiv/.config/configstore'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:789:18)
    at Function.sync (/usr/local/lib/node_modules/yo/node_modules/configstore/node_modules/mkdirp/index.js:71:13)
    at Object.create.all.get (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:41:13)
    at Object.Configstore (/usr/local/lib/node_modules/yo/node_modules/configstore/index.js:27:44)
    at new Insight (/usr/local/lib/node_modules/yo/node_modules/insight/lib/index.js:36:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/yo/lib/cli.js:117:15)
    at Module._compile (module.js:444:26)
    at Object.Module._extensions..js (module.js:462:10)
    at Module.load (module.js:339:32)
`````

I almost try all the solutions found on this issue #282,

thanks for your help.

**Comment by kevva** [comment]
https://github.com/yeoman/yeoman/issues/1097 https://github.com/yeoman/yeoman.io/issues/282 https://github.com/yeoman/yeoman/issues/1292

**Comment by radjivC** [comment]
Awesome thanks

**Comment by yoshiokatsuneo** [comment]
I got the same error when I run "yo" as "root" from "docker" container.
I end up editing "yo/node_modules/root-check/node_modules/downgrade-root/index.js" and removing "defaultUid()" not to setuid to default uid(1000 in Linux).

It is nicer if error message says that yeoman changed uid to 1000, and if there is option not to setuid.

```
module.exports = function () {
        if (isRoot() && process.setuid) {
                // var uid = parseInt(process.env.SUDO_UID, 10) || defaultUid();
                var uid = parseInt(process.env.SUDO_UID, 10)
                if (uid && uid > 0) {
                        process.setuid(uid);
                }
        }
};
```

Related issue #282 is somehow locked... So, I'm writing here...
