### ISSUE TITLE
codelab examples can no longer be compiled (step 8)

### ISSUE THREAD

**Issue by davie-robertson** [yeoman/yeoman.io#729]
node -v && npm -v
v7.10.0
4.6.1

Ubuntu 17.04 AMD64

```
[13:29:48] Loading /tank/public/development/mytodo/gulp_tasks/browsersync.js
[13:29:48] Loading /tank/public/development/mytodo/gulp_tasks/karma.js
[13:29:48] Loading /tank/public/development/mytodo/gulp_tasks/misc.js
[13:29:49] Loading /tank/public/development/mytodo/gulp_tasks/webpack.js
[13:29:49] Using gulpfile /tank/public/development/mytodo/gulpfile.js
[13:29:49] Starting 'default'...
[13:29:49] Starting 'clean'...
[13:29:49] Finished 'clean' after 16 ms
[13:29:49] Starting 'build'...
[13:29:49] Starting 'other'...
[13:29:49] Starting 'webpack:dist'...
[13:29:49] Finished 'other' after 140 ms
[13:30:04] Time: 15542ms
                                     Asset     Size  Chunks  Chunk Names
               app-093983fa26e09b6da555.js   103 kB       0  app
            vendor-093983fa26e09b6da555.js  3.98 MB       1  vendor
index-ee342089cd7ea3e109ad05bb7bd9d368.css  5.39 kB       0  app

WARNING in ./~/ajv/lib/async.js
96:20-33 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/async.js
119:15-28 Critical dependency: the request of a dependency is an expression

WARNING in ./~/uglify-js/tools/node.js
24:11-32 Critical dependency: the request of a dependency is an expression

WARNING in ./~/ajv/lib/compile/index.js
13:21-34 Critical dependency: the request of a dependency is an expression

WARNING in ./~/loader-runner/lib/loadLoader.js
3:2-28 Critical dependency: the request of a dependency is an expression

ERROR in (webpack)/lib/NormalModule.js
Module not found: Error: Can't resolve 'module' in '/tank/public/development/mytodo/node_modules/webpack/lib'
 @ (webpack)/lib/NormalModule.js 8:21-38
 @ (webpack)/lib ^.*$
 @ (webpack)/lib/webpack.js
 @ multi classnames es6-shim react react-dom react-redux react-router redux redux-localstorage webpack

ERROR in (webpack)/lib/node/NodeMainTemplateAsync.runtime.js
Module not found: Error: Can't resolve 'fs' in '/tank/public/development/mytodo/node_modules/webpack/lib/node'
 @ (webpack)/lib/node/NodeMainTemplateAsync.runtime.js 9:2-15 25:3-16
 @ (webpack)/lib ^.*$
 @ (webpack)/lib/webpack.js
 @ multi classnames es6-shim react react-dom react-redux react-router redux redux-localstorage webpack

ERROR in (webpack)/lib/node/NodeOutputFileSystem.js
Module not found: Error: Can't resolve 'fs' in '/tank/public/development/mytodo/node_modules/webpack/lib/node'
 @ (webpack)/lib/node/NodeOutputFileSystem.js 7:11-24
 @ (webpack)/lib ^.*$
 @ (webpack)/lib/webpack.js
 @ multi classnames es6-shim react react-dom react-redux react-router redux redux-localstorage webpack

...

``
```

**Comment by mischah** [comment]
Im having different issues with node `v6.10.2` and npm `5.5.1` running `npm run build`:

```
readline.js:973
            throw err;
            ^

Error: Command failed: npm run build
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at /usr/local/lib/node_modules/ntl/index.js:40:4
    at Array.forEach (native)
    at onPrompt [as completed] (/usr/local/lib/node_modules/ntl/index.js:39:10)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/ntl/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/ntl/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/ntl/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.onCompleted (/usr/local/lib/node_modules/ntl/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/ntl/node_modules/rx-lite/rx.lite.js:63:31)
```

Should be fixed in [FountainJS/generator-fountain-webapp](https://github.com/FountainJS/generator-fountain-webapp/issues).

cc/ @zckrs

**Comment by JoshuaKGoldberg** [comment]
The Codelab tutorial generally needs a major update, as noted in #789. We'll have to holistically overhaul them. Closing this out as a subset / duplicate of #789 since that'll capture this work. Cheers! 🎩
